# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    container_name: pg_container
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: post123gres
      POSTGRES_USER: postgres

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: post123gres
    ports:
      - "8082:80"

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8081:80